apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/depromeet/BEERAiR-gitops.git
    targetRevision: main
    path: argocd-resources/resources/app
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true