apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server
  namespace: test-server
  labels:
    app: test-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-server
  template:
    metadata:
      labels:
        app: test-server
    spec:
      containers:
        - name: test-server
          image: zeze1004/sulsul:latest
          imagePullPolicy: Always
          imagePullSecrets: regcred
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 30"]