apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-server
  namespace: argocd
spec:
  project: apps
  source:
    path: test-server
    repoURL: https://github.com/depromeet/BEERAiR-gitops.git
    targetRevision: main
  destination:
    name: in-cluster
    namespace: test-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true